import { CITIES } from '../const/cities.js';
import { CityType, GoodsType, Offer, OfferType, UserType } from '../types/index.js';

export function createOffer(offerData: string): Offer {
  const [
    title,
    description,
    date,
    city,
    preview,
    images,
    isPremium,
    isFavorite,
    rating,
    type,
    rooms,
    guests,
    price,
    goods,
    name,
    email,
    avatar,
    userType,
    password,
    commentsCount,
    latitude,
    longitude,
  ] = offerData.replace('\n', '').split('\t');
  return {
    title,
    description,
    date: new Date(date),
    city: CITIES[city as CityType],
    preview,
    images: images.split(';'),
    isPremium: !!Number(isPremium),
    isFavorite: !!Number(isFavorite),
    rating: Number(rating),
    type: type as OfferType,
    rooms: Number(rooms),
    guests: Number(guests),
    price: Number(price),
    goods: goods.split(';').map((key) => GoodsType[key as keyof typeof GoodsType]),
    author: {
      name,
      email,
      avatar,
      type: userType as UserType,
      password,
    },
    commentsCount: Number(commentsCount),
    latitude: Number(latitude),
    longitude: Number(longitude),
  };
}
